[package]
name = "aoc-2021"
version = "0.1.0"
edition = "2021"
authors = ["Tim Armstrong <git.tim.armstrong@gmail.com>"]

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"


[dependencies]
